version: '3.7'

services:
  index_page:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    container_name: index_page
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
networks:
  env_network:
    external: true